# Project Information
pluginGroup=dev.franzin
pluginVersion=0.5.1
pluginDescription=Adds a craftable spyglass that lets you zoom in and scout the world from afar.
hytaleVersion=0.6.3

# Gradle Configuration
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
